---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audit-radar.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-ui-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "audit-radar.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["audit-alerter-config"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["audit-alerter-secret"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-ui-configmap
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: audit-ui
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: audit-ui-configmap
